### ISSUE TITLE
Min. Max. wrong

### ISSUE THREAD

**Issue by Magistnix** [tebjan/TimerTool#1]
Hi, 
please note: f=1/t 
Please change  Line 42/43 from MainForm.cs to
        MinLabel.Text = "Max: " + (caps.PeriodMin/10000.0) + " ms";
        MaxLabel.Text = "Min: " + (caps.PeriodMax/10000.0) + " ms";
Thanks

**Comment by tebjan** [comment]
hi @Magistnix this depends on the perspective. i've thought about it when writing the code and min/max is correct as is when you think about it as a period. i think there is no real right and wrong...

**Comment by tebjan** [comment]
i've changed it anyway :)
