### ISSUE TITLE
Can this tool be used to enforce higher latency timers?

### ISSUE THREAD

**Issue by chrcoluk** [tebjan/TimerTool#2]
So windows 8.1 boots up at 2ms timer resolution, I get no coil whine at 2ms (but I do get it at 1ms or lower) and better idle power usage and temps.  Also lower latency timers can hurt performance, its not a always gain situation.

But it seems microsoft have given app developers a lot of power, apps even without admin power can adjust the timer, e.g. steam and chrome will change it to 1ms latency.

Is there a way for this app to override those apps and force 2ms or even higher latency timer?

**Comment by tebjan** [comment]
as far as i know the timer is always the smallest value set by any application. there is no way to enforce slower counters. this also makes sense in terms of reliability, if you develop an application that is time critical and needs 1 ms timer resolution it would be problematic if another app would just set a slower counter. so if you want a slower counter you need to find the app that sets the low counter values and close it. well known for that is chrome and skype.
